apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dm1
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: springdemo
    tags.datadoghq.com/version: "1.0"
  name: 
    sbdemo-apserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbdemo-apserver
  template:
    metadata:
      labels:
        app: sbdemo-apserver
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: springdemo
        tags.datadoghq.com/version: "1.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.21.0
    spec:
      containers:
      - name: apserver
        image: isaac0815/springdemo:apserver
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: DB_URL
            value: "jdbc:postgresql://sbdemo-postgres-service:5432/demodb?user=postgres&password=postgres"
          - name: PIC_DIR
            value: "/opt/picDir"
          - name: REDIS_HOST
            value: "sbdemo-redis-service"
          - name: REDIS_PORT
            value: "6379"   
          - name: LOGGING_LEVEL_ROOT
            value: DEBUG
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"            
        volumeMounts:
          - mountPath: "/opt/picDir"
            name: apserver-pvc
      volumes:
      - name: apserver-pvc
        persistentVolumeClaim:
          claimName: sbdemo-apserver-pvc
