apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sbdemo-apserver-pvc
  namespace: todoweb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
